services:
  - type: web
    name: chevrolet-uz
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    releaseCommand: "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: your-app-name.onrender.com
