# Generated by Django 6.0.6 on 2026-06-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Rasm')),
                ('image_mobile', models.ImageField(blank=True, upload_to='news/mobile/', verbose_name='Mobil rasm')),
                ('url_path', models.CharField(blank=True, max_length=200, verbose_name="URL yo'li")),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr etilgan')),
                ('is_slider', models.BooleanField(default=False, verbose_name="Slider'da ko'rsatish")),
                ('slider_order', models.PositiveIntegerField(default=0, verbose_name='Slider tartibi')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Aksiya nomi')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, upload_to='offers/', verbose_name='Rasm')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Foiz stavkasi (%)')),
                ('min_down_payment', models.PositiveIntegerField(blank=True, null=True, verbose_name="Minimal boshlang'ich to'lov (%)")),
                ('max_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal muddat (oy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='cars.car', verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': 'Maxsus taklif',
                'verbose_name_plural': 'Maxsus takliflar',
                'ordering': ['-created_at'],
            },
        ),
    ]
