# Generated by Django 6.0.6 on 2026-06-25 04:52

import django.core.validators
import django.db.models.deletion
import main.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brend nomi')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Brend logotipi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Avtomobil brendi',
                'verbose_name_plural': 'Avtomobil brendlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon_class', models.CharField(blank=True, help_text='Masalan: bi-car-front', max_length=50, verbose_name='Bootstrap Icon klassi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Chevrolet Tracker 2024', max_length=200, verbose_name='Mashina nomi')),
                ('model_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ishlab chiqarilgan yil')),
                ('slug', models.SlugField(help_text="Avtomatik to'ldiriladi", max_length=250, unique=True, verbose_name='Slug (URL)')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Qisqa tavsif')),
                ('full_description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Narxi (USD)')),
                ('price_uzs', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Narxi (UZS)')),
                ('is_price_negotiable', models.BooleanField(default=False, verbose_name='Narx kelishiladi')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, help_text='Masalan: 1.5', max_digits=3, null=True, verbose_name='Dvigatel hajmi (L)')),
                ('engine_power_hp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quvvat (ot kuchi)')),
                ('engine_power_kw', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quvvat (kVt)')),
                ('engine_torque', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Burovchi moment (Nm)')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('hybrid', 'Gibrid'), ('electric', 'Elektr'), ('gas', 'Gaz (LPG/CNG)')], default='petrol', max_length=10, verbose_name="Yoqilg'i turi")),
                ('fuel_consumption_city', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Shahar sarfi (L/100km)')),
                ('fuel_consumption_highway', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Magistral sarfi (L/100km)')),
                ('transmission', models.CharField(choices=[('AT', 'Avtomat'), ('MT', 'Mexanik'), ('CVT', 'Variator (CVT)'), ('DSG', 'Robot (DSG)')], default='AT', max_length=5, verbose_name='Uzatmalar qutisi')),
                ('gears_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Pog'onalar soni")),
                ('drive_type', models.CharField(choices=[('FWD', "Old g'ildirak"), ('RWD', "Orqa g'ildirak"), ('AWD', "To'liq yurish (AWD)"), ('4WD', '4x4 (4WD)')], default='FWD', max_length=5, verbose_name='Yurish turi')),
                ('acceleration_0_100', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='0–100 km/s (soniya)')),
                ('max_speed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maksimal tezlik (km/s)')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Uzunlik (mm)')),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kengligi (mm)')),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Balandligi (mm)')),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name="G'ildiraklar oralig'i (mm)")),
                ('curb_weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name="Snaryad og'irligi (kg)")),
                ('trunk_volume_l', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bagaj hajmi (litr)')),
                ('fuel_tank_l', models.PositiveIntegerField(blank=True, null=True, verbose_name="Yoqilg'i baki (litr)")),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Rang')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol (saytda ko'rinsin)")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan (featured)')),
                ('is_new', models.BooleanField(default=True, verbose_name='Yangi model')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='main.carbrand', verbose_name='Brend')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='main.carcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.car_image_upload_path, verbose_name='Rasm')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt matn (SEO uchun)')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.car', verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': 'Avtomobil rasmi',
                'verbose_name_plural': 'Avtomobil rasmlari',
                'ordering': ['-is_main', 'order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug (URL)')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Qisqacha mazmun')),
                ('content', models.TextField(verbose_name="To'liq matn")),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=main.models.news_image_upload_path, verbose_name='Muqova rasmi')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr etilgan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Muhim yangilik')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="Ko'rishlar soni")),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('related_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='main.car', verbose_name="Bog'liq avtomobil")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='main.newscategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=main.models.avatar_upload_path, verbose_name='Profil rasmi')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name="O'zim haqimda")),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon raqam to'g'ri formatda kiriting: '+998901234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon raqami')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['slug'], name='main_car_slug_cc1ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_active', 'is_featured'], name='main_car_is_acti_4888fb_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'category'], name='main_car_brand_i_f2458d_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='main_news_slug_27ce91_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published', 'is_featured'], name='main_news_is_publ_f361fc_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published_at'], name='main_news_publish_65045a_idx'),
        ),
    ]
