# Generated by Django 6.0.6 on 2026-06-25 11:21

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Katta banner ustidagi asosiy matn', max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Kichik sarlavha')),
                ('image', models.ImageField(help_text="Tavsiya etilgan o'lcham: 1920×900 px. JPEG yoki WebP formati.", upload_to=main.models.banner_image_upload_path, verbose_name='Banner rasmi')),
                ('button_text', models.CharField(blank=True, default="Batafsil ko'rish", max_length=80, verbose_name='Tugma matni')),
                ('button_url', models.CharField(blank=True, default='/cars/', max_length=300, verbose_name='Tugma havolasi (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Kichik son — birinchi ko'rsatiladi", verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Bannerlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
