# Generated by Django 6.0.6 on 2026-06-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Viloyat nomi')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Diler nomi')),
                ('market_type', models.CharField(choices=[('local', 'Ichki bozor'), ('export', 'Tashqi bozor'), ('parts', 'Ehtiyot qismlar'), ('parts_export', 'Ehtiyot qismlar (tashqi bozor)')], default='local', max_length=20, verbose_name='Bozor turi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Ish vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealers.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Diler',
                'verbose_name_plural': 'Dilerlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Servis markazi nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_centers', to='dealers.dealer', verbose_name='Diler')),
            ],
            options={
                'verbose_name': 'Servis markazi',
                'verbose_name_plural': 'Servis markazlari',
            },
        ),
    ]
