# Generated by Django 6.0.6 on 2026-06-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan / Cars'), ('lcv', 'LCV (Yengil tijorat)')], max_length=20, verbose_name='Turi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model nomi')),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha nom")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, upload_to='cars/', verbose_name='Rasm')),
                ('base_price', models.BigIntegerField(verbose_name="Boshlang'ich narx (so'm)")),
                ('discounted_price', models.BigIntegerField(blank=True, null=True, verbose_name="Chegirma narxi (so'm)")),
                ('discount_amount', models.BigIntegerField(blank=True, null=True, verbose_name="Chegirma miqdori (so'm)")),
                ('status', models.CharField(choices=[('active', 'Faol'), ('soon', 'Tez Kunda'), ('discontinued', "To'xtatilgan")], default='active', max_length=20, verbose_name='Holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Bosh sahifada ko'rsatish")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('url_path', models.CharField(blank=True, max_length=100, verbose_name="Sayt URL yo'li")),
                ('online_buy_url', models.URLField(blank=True, verbose_name='Onlayn xarid URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rang nomi')),
                ('hex_code', models.CharField(help_text='#RRGGBB formatda', max_length=7, verbose_name='HEX kod')),
                ('image', models.ImageField(blank=True, upload_to='car_colors/', verbose_name='Rasm')),
                ('price_addition', models.BigIntegerField(default=0, verbose_name="Qo'shimcha narx (so'm)")),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='cars.car', verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_gallery/', verbose_name='Rasm')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cars.car', verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xususiyat nomi')),
                ('value', models.CharField(max_length=200, verbose_name='Qiymat')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name="O'lchov birligi")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cars.car', verbose_name='Avtomobil')),
            ],
            options={
                'verbose_name': 'Texnik xususiyat',
                'verbose_name_plural': 'Texnik xususiyatlar',
                'ordering': ['order'],
            },
        ),
    ]
